source/workbook/tests/test_workbook.hpp
source/workbook/workbook.cpp

Add implement const version of `workbook::get_sheet_by_name()`.
and non const version are based on const version.

Add implement const version of workbook::get_sheet_by_name().

---

cmake/xlnt.cmake

BTW, I found that `XLNT_EXPORT` defined in `cmake/xlnt.cmake` is not used.
Does `XLNT_EXPORT` meant to do this?

Fixes visual studio static compile warings about dll interface.

---

include/xlnt/cell/index_types.hpp
source/cell/index_types.cpp

1. Make binary arithmetic operators for column_t non-member and depends on compound assignments ( [1](http://en.cppreference.com/w/cpp/language/operators), [2](http://stackoverflow.com/a/4421719/87021) ).
2. Remove doc comments in index_types.cpp.

Refactor index types

---

include/xlnt/workbook/const_worksheet_iterator.hpp
include/xlnt/workbook/worksheet_iterator.hpp
include/xlnt/worksheet/cell_iterator.hpp
include/xlnt/worksheet/const_cell_iterator.hpp
include/xlnt/worksheet/const_range_iterator.hpp
include/xlnt/worksheet/range_iterator.hpp

1. we have overloaded operator*() for all iterators, returning a value type T (not a reference).
2. we use the std::reverse_iterator, its operator*() returns a reference type, by default the reference type is T&.
follow implement  std::reverse_iterator::operator*() const are taken form VS2015:
```C++
// in class reverse_iterator
reference operator*() const
{ // return designated value
_RanIt _Tmp = current;
return (*--_Tmp);
}
```
The `_RanIt` is our base non reverse iterators, the type of `(*--_Tmp)` is `T`. and the `reference` is `T&`. This cause
> warning C4172: returning address of local variable or temporary
And it is bug.
This commit specifies explicitly the 5th template argument for all our iterators base class like `std::iterator<tag,T, ptrdiff_t, T*, T>`.
It make the `reference` …

Fixes type for all iterator::reference.

---

source/cell/cell_reference.cpp
source/cell/index_types.cpp
source/detail/serialization/xlsx_consumer.cpp

closes #206
closes #203
@tfussell  - I can break this up into smaller pieces if you want, it was easier profiling to keep stacking changes on top of each other.
On my machine (Windows, non SSD), this takes reading the attached file from ~3.2s to ~1.9s.  Below is a link to the bench script I was profiling against
https://gist.github.com/chris-b1/b49e43536938826d14c8340b808ed05f
[floats.xlsx](https://github.com/tfussell/xlnt/files/1253776/floats.xlsx)
After this the profile graph seems pretty flat, bulk of time happening inside the xml parsing stuff.

PERF: optimize read_cell

---

source/detail/cryptography/compound_document.cpp
source/detail/serialization/miniz.cpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/zstream.cpp
source/styles/color.cpp
source/utils/date.cpp
source/utils/time.cpp
third-party/libstudxml/xml/parser
third-party/libstudxml/xml/parser.ixx

switched to nullptr instead of NULL or 0.
Switch some expressions using ',' to multiple statements separated by ';'
Removed unused template function
Used override keyword for some overridden virtual functions.

Issue #216-cleanup for Clang 5.0 build

---

source/detail/serialization/xlsx_consumer.cpp

Hello
I've been trying to use the xlnt library, however it failed for some of my inputs.
After some digging I've found out that the attribute present in this PR was missing.
I'm well aware that this is not a fix, but it might be usefull for developers to properly fix it.
Why is the default behaviour of missing attributes to raise an exception and fail to load?

Parse readingOrder

---

source/workbook/workbook.cpp
tests/workbook/workbook_test_suite.hpp

- Worksheet ID now generated from the maximum of existing IDs
- Worksheet ID no longer copied from existing sheet
- Added tests

Fix for issue #228: Worksheet ID is not always unique

---

source/detail/serialization/miniz.cpp

Fixes the following error I was getting when building on my system:
```
source/detail/serialization/miniz.cpp:2098:50: error: cast from 'const void *' to 'unsigned char *' drops const qualifier [-Werror,-Wcast-qual]
tdefl_compress_buffer(pComp, (mz_uint8 *)pImage + (flip ? (h - 1 - y) : y) * bpl, bpl, TDEFL_NO_FLUSH);
^
1 error generated.
```

fix -Wcast-qual in miniz

---

source/detail/serialization/custom_value_traits.hpp

Values like lightGray will match with lightgray.  Unexpected inputs will
be ignored and return none.
Needs prama to clang to be happy.

custom_value_traits.hpp: pattern_fill from_string() ignores case

---

.travis.yml
CMakeLists.txt
include/xlnt/worksheet/phonetic_pr.hpp
source/CMakeLists.txt
source/cell/rich_text.cpp
source/detail/serialization/xlsx_producer.cpp
source/detail/serialization/zstream.cpp
source/styles/font.cpp
source/worksheet/phonetic_pr.cpp
source/worksheet/worksheet.cpp
tests/CMakeLists.txt

Resolves #147 by adding CI builds extending compiler coverage to GCC (6-8), as well as Clang (4-6)
Additionally, the C++ language standard is modified as follows
| GCC | Clang | C++ Standard |
| --- | --- | --- |
| 6 | 4 | c++11 |
| 7 | 5 | c++14 |
| 8 | 6 | c++17 |
* build times for each individual job are reduced by 60-90 seconds mostly due to passing -j2 with the build arguments (2 additional jobs do increase total time slightly)
* All warnings and compiler errors generated have either been resolved or suppressed (Additional Clang Weverything suppressions: Wfloat-equal, Wnewline-eof, Wcovered-switch-default, Wexit-time-destructors, and Wmissing-braces). Wfloat-equal should be considered, but the rest are all either irrelevant (eof post c++11, switch default, exit-time-dtors), or …

Travis CI improvements

---

include/xlnt/utils/optional.hpp
source/CMakeLists.txt
source/detail/serialization/xlsx_consumer.cpp
tests/utils/optional_tests.cpp

Resolution to #300
With this PR, any type that can be moved or copied can be used with optional.
This is a relatively simple version of optional in that it doesn't support in place construction (variadic forwarding of parameters) or constexpr. A well tested third party lib (boost/optional-lite/?) should be used if these become limitations as they add significant complications when combined with compiler support requirements

Optional implementation that doesn't require default constructors

---

include/xlnt/styles/color.hpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/xlsx_producer.cpp
source/styles/color.cpp

Resolves #277 
Make tint explicitly optional (returning a default of 0.0 / no tint if not set) and checking serialisation/deserialisation of all color attributes

Ensure <color tint=...> is correctly serialised as an optional double

---

include/xlnt/workbook/worksheet_iterator.hpp
include/xlnt/worksheet/cell_iterator.hpp
include/xlnt/worksheet/range_iterator.hpp
source/worksheet/cell_iterator.cpp
source/worksheet/range_iterator.cpp
tests/workbook/workbook_test_suite.cpp
tests/worksheet/worksheet_test_suite.cpp

Resolves #256 
C++ standard requires Fwd iterators and better to be default constructible. The only defined requirement is that two default constructed iterators compare equal (everything else is defined per container).
This implementation compares false against non-default iterators, and functions other than equality are undefinied

Iterator default ctors

---

include/xlnt/cell/comment.hpp
source/cell/cell.cpp
source/cell/comment.cpp
tests/cell/cell_test_suite.cpp

Resolves #282 
I find it debatable but acceptable for position to be set (and not part of the equality comparison). At the very least, the use of absolute offsets prevents a sensible default value being used (could equality compare relative position? Would that make sense?).

Don't set comment size on explicit overload

---

source/cell/cell.cpp
tests/cell/cell_test_suite.cpp

Resolves #327 
Remove the exclusion on hyperlink text that doesn't include a ':' character

Relative hyperlinks

---

source/workbook/workbook.cpp

The current implementation of `rel_id_sorter` incorrectly returns true whenever `lhs.id()` is longer but starts with a lower digit than `rhs.id()`. For example "rId11 < rId2". This in turn causes std::sort to crash with a confusing segfault (under MinGW 7.3.0).
This is fixed by checking for both shorter and longer id string.
This issue only appears when adding more than about 15-20 worksheets to the workbook.

Fix relationship sorting

---

source/detail/number_format/number_formatter.cpp
source/utils/date.cpp
tests/styles/number_format_test_suite.cpp
tests/utils/datetime_test_suite.cpp

Resolves #254 
Some of the unit tests for number/date formatting were wrong and after resolving those I discovered that the actual calculations was not correct. Instead I replaced using ctime which should be pretty reliable.

Corrected the calculation and formatting of weekdays

---

cmake/XlntConfig.cmake.in
source/CMakeLists.txt

Issue #331 
Install xlnt, then any dependent cmake-using package can link up with:
```cmake
find_package(Xlnt)
target_link_libraries(foo PRIVATE xlnt::xlnt)
```
There's still plenty to do to make xlnt modern cmake, but this should help.

Export xlnt::xlnt target when installed.

---

.travis.yml
source/detail/serialization/custom_value_traits.cpp

Resolves #335 
As noted in the linked issue, a single naming issue was preventing xlnt compiling on GCC5. This PR resolves that and adds GCC5 to the CI matrix

GCC5 compatibility + CI

---

CMakeLists.txt
tests/CMakeLists.txt

I added a few lines to CMakeLists.txt in ./tests and in the project root to support using CTest as a test driver. This change shouldn't impact the code or the existing build process; all tests pass (Linux Mint 19.1, clang version 6.0.0-1ubuntu2, x86_64-pc-linux-gnu)

Added CTest support

---

source/detail/serialization/custom_value_traits.cpp

I suffered from a bug like #385. Build fails as shown below.
```bash
/home/yschung/lib/xlnt/source/detail/serialization/custom_value_traits.cpp:350:10: error: ‘orientation’ is not a class, namespace, or enumeration
case orientation::default_orientation:
```
In my opinion, this issue is not a grammatically incorrect BUG. This is compiler issue.
My environment was g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 201609.
I've tested with some other compiler settings. The issue does not occur with **g++6 and clang**.
However, as I modified xlnt namespace explicitly, the build was successful in g++ 5.4 (I don't know why.)
```c++
// case orientation::default_orientation:
case xlnt::orientation::default_orientation:
return "default";
// case orientation::landscape:
case xlnt::orientation::landscape: …
```

Fixed gcc 5 build bug

---

benchmarks/spreadsheet-load.cpp
include/xlnt/styles/format.hpp
include/xlnt/utils/numeric.hpp
include/xlnt/utils/optional.hpp
include/xlnt/worksheet/sheet_format_properties.hpp
source/detail/header_footer/header_footer_code.cpp
source/detail/implementations/cell_impl.hpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/xlsx_consumer.hpp
source/detail/serialization/xlsx_producer.cpp
source/worksheet/page_margins.cpp
source/worksheet/page_setup.cpp
source/worksheet/worksheet.cpp
tests/detail/numeric_util_test_suite.cpp
tests/workbook/serialization_test_suite.cpp

I've had reason to utilise xlnt again recently, this time commonly with MB+ size xlsx files and the slow loading time was really starting to bite. Did some benchmarking, found the majority of the time taken was spent in the XML parsing library while (at the time) creating the xlnt::worksheet was only ~10-15% of the workload
Following the examples from libstudxml docs, I rewrote the segment of the parser that loads rows/cells. This roughly tripled (3x) the throughput of the XML library, and cut the load-spreadsheet benchmark time nearly in half (~60% of original). [This commit](https://github.com/Crzyrndm/xlnt/commit/fa58994a1424239094d6ab3b726f8c05b34584db) adds the benchmark used to establish the improvements before any other changes are made
Benchmarking also highlighted …

Accelerated worksheet parsing

---

benchmarks/CMakeLists.txt
benchmarks/microbenchmarks/CMakeLists.txt
benchmarks/microbenchmarks/double_to_string.cpp
benchmarks/microbenchmarks/string_to_double.cpp
benchmarks/spreadsheet-load.cpp
include/xlnt/cell/index_types.hpp
include/xlnt/utils/numeric.hpp
include/xlnt/worksheet/range_reference.hpp
source/cell/cell.cpp
source/cell/index_types.cpp
source/detail/header_footer/header_footer_code.cpp
source/detail/header_footer/header_footer_code.hpp
source/detail/implementations/cell_impl.hpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/xlsx_consumer.hpp
source/detail/serialization/xlsx_producer.cpp
source/detail/serialization/xlsx_producer.hpp
source/worksheet/range_reference.cpp
source/worksheet/worksheet.cpp
tests/detail/numeric_util_test_suite.cpp

This is a continuation of some of the work I did for #421 / #422 a few months ago
Adds a microbenchmark project (enabled by passing -DBENCHMARKS=ON -DXLNT_MICROBENCH_ENABLED=ON to cmake). It uses [google banchmark](https://github.com/google/benchmark). Currently used to compare a variety of ways of (de)serialising numbers.
* gbenchmark dependency aquired using cmake FetchContent module (requires cmake 3.11 as  indicated by the [script](https://github.com/tfussell/xlnt/blob/e8cb8d9bc6f4ac3ce93c77f63a435f0081eefaf0/benchmarks/microbenchmarks/CMakeLists.txt)). find_package is nearly useless on windows, so it was the most hassle free method for a "developer only" tool I could find. I'm open to suggestions on acquisition method
Note: the std::<to/from>_chars and *_comma* benchmarks are …

microbenchmarks for double<->string conversion, serialisation improvements

---

include/xlnt/utils/numeric.hpp
source/cell/cell.cpp
source/detail/number_format/number_formatter.cpp
source/detail/number_format/number_formatter.hpp
source/detail/serialization/serialisation_helpers.hpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/xlsx_producer.cpp
source/detail/serialization/xlsx_producer.hpp

Unlike recent PR's from me, this is almost entirely a correctness improvement.
With this branch, local runs of the test suite have no failures even when the locale is changed to one which uses the comma character as its decimal separator (i.e. passes with set_locale(LC_ALL, "de-DE") on windows. the german locale name may be different on other platforms)
This is done by removing all usages of the following functions when applied to floating point types (e.g. double) to convert them to a string representation
* std::stringstream
* std::to_string
* s*printf
Instead these number_serialiser::serialise and number_serialiser::serialise_short use the same technique of coverting the comma to a decimal point when required as was used in #421 to affect the reverse transformation (string->double)
I'm …

locale aware double->string conversions

---

source/CMakeLists.txt

Otherwise, XLNT_INCLUDE_INSTALL_DIR is not set correctly and find_package(Xlnt) results to an error:
```
CMake Error at /usr/lib64/cmake/xlnt/XlntConfig.cmake:23 (message):
File or directory include referenced by variable XLNT_INCLUDE_DIR does not
exist !
Call Stack (most recent call first):
/usr/lib64/cmake/xlnt/XlntConfig.cmake:41 (set_and_check)
CMakeLists.txt:4 (find_package)
```
The content of the line 41 of /usr/lib64/cmake/xlnt/XlntConfig.cmake is: `set_and_check(XLNT_INCLUDE_DIR "include")`. 
I'm using the Arch Linux user repository package https://aur.archlinux.org/packages/xlnt/.
The used build manual is described here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xlnt.

Fix XLNT_INCLUDE_INSTALL_DIR

---

source/detail/number_format/number_formatter.cpp

LibreOffice use color names in upper case. It is desirable to support this format

LibreOffice color names support

---

.gitignore
CMakeLists.txt
include/xlnt/worksheet/page_setup.hpp
source/detail/serialization/xlsx_consumer.cpp
source/detail/serialization/xlsx_producer.cpp
source/worksheet/page_setup.cpp
tests/worksheet/page_setup_test_suite.cpp

@tfussell Please check if you want to merge this change:
Fixing one issue - when loading an existing file as a template and save it, some print settings are lost.

Fix - Print Settings (Page Size, margins, etc) not saved when loading a file and save it.

---

source/detail/serialization/xlsx_consumer.cpp

Example of XML code from an Excel sheet:
```
<c r="G4" s="5" t="s">
<v>45</v>
</c>
<c r="H4"/>
<c r="I4" s="1">
<v>3</v>
</c>
```
When using the xlnt::streaming_workbook_reader, the streaming_cell_ was previously reused, but was overwritten with information from the new cell. In the example above, reading cell G4 would read a shared_string at index 45. Cell H4 is a cell with no information except its reference, and would previously cause XLNT to return cell H4 with the information from cell G4.
The simple fix I provided resets the cell state, so that the streaming cell always begins with a clean state, just as it happens when not streaming.

The streaming cell now always begins with a clean state when using the xlnt::streaming_workbook_reader

---

source/detail/number_format/number_formatter.cpp
source/detail/number_format/number_formatter.hpp

Explanation: https://bz.apache.org/ooo/show_bug.cgi?id=70003
This fixes issues with some locales where "system default" is the default setting for times and dates. This happens, for example, when using German (Austria) as a locale in Windows, or when setting it manually in Excel.
Especially when languages such as German (Austria) are used, where the "system default" is used for such types, the user is not aware of the locale and the probability of creating an Excel file that cannot be loaded by XLNT is very high.
This pull request fixes this issue.

Added support for the System Default locale for the Time and Long Date types

---

source/detail/number_format/number_formatter.cpp

Limits isn't being transitively included on gcc 11.2.0/ubuntu.  Added as it produces an error

Missing include in number_formatter.cpp

---

source/styles/format.cpp

In case number_format() is called on a format that does not have a value format set, number_format() calls d_->number_format_id.get() on an invalid number_format_id or dereferences d_->parent->number_formats.end() causing a crash.
This can happen when calling cell::is_date() on a cell that has type 'number' without a number format but some other styling set.
This might never occur in spreadsheet files created by commercial applications but xlnt certainly allows to create such a file.
We therefore fix number_format by returning the general number format as a fallback.
Additionally, consider to add a method format::has_number_format() and change cell::is_date() accordingly.
Attached there is a test file were the problem occurs when cell::is_date() is called on cell A1. …

Fix format::number_format

---

source/detail/serialization/xlsx_producer.cpp

Very minor fix to xlsx_producer.cpp to add the already existing attribute to the xlsx file when it is being generated.

fix writing of missing showGridLines attribute to xlsx file

---

source/detail/serialization/xlsx_consumer.cpp

Previously my philosophy had been to do what Excel does when parsing a document. Given the kinds of problems people are running into, I now think it's better to lean towards being more permissive with parsing. For this reason, I'm removing the logic to check merged cell count. Also count is optional which causes problems reading worksheets from other spreadsheet software.
Fixes https://github.com/tfussell/xlnt/issues/640

Ignore merge cell count

---

docs/introduction/Installation.md

The project uses submodules but if you download the repo as a zip from Github it doesn't pull the submodules which leads to issues like #642.
Docs should reflect the correct way to build from source

Update documentation to make building from source clearer

---

tests/detail/numeric_util_test_suite.cpp

Fixes warning C4305: 'initializing': truncation from 'double' to 'float'
Fixes warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data

Fixes float warnings

---

third-party/miniz/miniz.c

Fixes warning C4127: conditional expression is constant

Fixes warning C4127: conditional expression is constant
