docs/samples/sample1.cpp

Just a small update so the supplied sample will compile

Update sample1.cpp so it will compile

---

README.md

Latest versions of premake are now on github. Minor readme modification.

Premake has moved to github

---

appveyor.yml
cmake/xlnt.cmake
include/xlnt/xlnt_config.hpp

and cleanup for appveyor build script.

Enable static build for appveyor.

---

include/xlnt/styles/format.hpp
include/xlnt/styles/style.hpp
source/detail/format_impl.hpp
source/detail/style_impl.hpp
source/detail/xlsx_consumer.cpp
source/detail/xlsx_producer.cpp
source/styles/format.cpp
source/styles/style.cpp

sorry, for the recommit of some cleaning due bad pull/push

autofilter skip remaining in stage, style attribute "pivotButton" "quotePrefix"

---

docs/introduction/Examples.md
docs/introduction/Installation.md

This pull request is in relation to issue - Improve documentation #65 - the new content provides xlnt installation instructions (for Ubuntu) and also provides a really simple "read spread sheet" example for new xlnt users. From my experience a lot of users enjoy the agility of Ubuntu as a development environment and it is for this reason that I have concentrated on Ubuntu.
Future content will provide more complex read examples, writing examples and high performance examples including reading and writing spread sheets with 10s of thousands of rows and in addition using spread sheets as lookups (making decisions based on values in a spread sheet; similar to what VLOOKUP does, but more scalable).
Kind regards
Tim

Documentation 

---

AUTHORS.md
docs/introduction/Examples.md
docs/introduction/Installation.md

Congratulations on the version 1 release, and the 1000 commit milestone. Looking forward to contributing on version 1 and beyond.

Updating documentation after installing and testing the new 1.x.x version of xlnt

---

xlntpyarrow/xlntpyarrow.cpp

xref #184 - minor fix to get things running locally for me

import_pyarrow returns error code, not bool

---

CMakeLists.txt
include/xlnt/workbook/workbook_view.hpp
source/CMakeLists.txt
source/detail/serialization/xlsx_consumer.cpp

fix #204 #205

---

source/detail/serialization/xlsx_producer.cpp

Closes #235.  
It seems weird to me that for a column width to take effect customWidth need not be set, while the opposite is true for rows (/customHeight).  
However, I feel like this is the expected behavior, although I guess the custom_height field could be removed completely (?).

Setting the height of a row now produces the expected result.

---

source/detail/serialization/xlsx_consumer.cpp

remove from skip_attributes list

bestFit change

---

include/xlnt/cell/index_types.hpp
include/xlnt/worksheet/worksheet.hpp
source/worksheet/worksheet.cpp
tests/worksheet/worksheet_test_suite.cpp

I've added a new set of methods on the worksheet class to allow inserting new rows and/or columns and also deleting existing ones.
Relevant tests also included.

Added new feature to insert or delete rows / columns

---

source/detail/cryptography/compound_document.cpp

Resolves #165
Removed some duplicate code where it reads data from the compound document streambuf

Removed duplicate code in compound document

---

source/cell/cell_reference.cpp
tests/cell/cell_test_suite.cpp

this solves issue https://github.com/tfussell/xlnt/issues/449

fix cell reference parsing

---

source/packaging/ext_list.cpp

Fixed an exception that was thrown when the property's namespace is a web address.

---

include/xlnt/utils/optional.hpp
source/detail/cryptography/sha1.c
source/detail/cryptography/sha512.c
source/detail/serialization/custom_value_traits.hpp

Fixes https://github.com/tfussell/xlnt/issues/487

Fix GCC 4.8.2 build problems

---

include/xlnt/worksheet/worksheet.hpp
source/worksheet/worksheet.cpp
tests/worksheet/worksheet_test_suite.cpp

resolves https://github.com/tfussell/xlnt/issues/484

Issue #484 include first empty rows and columns in range if skip_null false

---

docs/introduction/Examples.md

Instead of <pre>\`\`\`</pre> one can write <pre>\`\`\`c++</pre> and then the syntax highlighter kicks in

add c++ code syntax highlighting

---

source/detail/serialization/xlsx_producer.cpp

Fixes clang compiler warning: `/Users/thomas/Development/xlnt/source/detail/serialization/xlsx_producer.cpp:680:27: 34 enumeration values not handled in switch: 'unknown', 'core_properties', 'extended_properties'...`. Also cleans up some nearby code and adds comments.

Fix unhandled enumeration values in switch statement

---

include/xlnt/cell/cell_reference.hpp

Fixes https://github.com/tfussell/xlnt/issues/463
Fixes https://github.com/tfussell/xlnt/issues/486

Import functional in cell_reference.hpp to fix build

---

source/worksheet/range_iterator.cpp

Closes https://github.com/tfussell/xlnt/issues/483

Fix bug in decrement method of range_iterator for column-major order
